spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wbc?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:user_test.sql
#      - classpath:user_test1.sql
#    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobaDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
